### PR TITLE
Updated dependencies and some refactoring

### PR DESCRIPTION
**Pull request by mark-win**
Main differences:
- phpunit 7.4
- switched money to official follow up project in newest version
- refactored to PSR-4 autoloading

### CODE REVIEW

**Comment by mark-win** [comment]
I root for dropping php <= 7.0 support. Mind me dropping lower versions from .travis.yml?

**Comment by amenk** [comment]
@mark-win We can bump the Module Major version and drop deprecated PHP Versions

**Comment by amenk** [comment]
Maybe we should rebase this onto https://github.com/Mestrona/aqbanking-php/tree/feature/aqbanking-5_99

**Comment by amenk** [comment]
@mark-win  Are yo ustill interested in this? We should rebase it on aqbanking-5_99 ... and we can drop everything below PHP 7.2 which is not longer security-supported.

**Comment by grummbeer** [comment]
> PHP 7.2 which is not longer security-supported.

Now drop all below 8.1? Would do it.

**Pull request closed without merging**
